[project]
build = "none"
strip_output = """
Use default settings!
"""

[[tests]]
name = "max2"
input = ["java", "-cp", "$digital", "CLI", "test", "max2.dig", "-tests", "$project_tests/max2_test.dig"]
expected = """
max2_test: passed
"""
rubric = 25 

[[tests]]
name = "1_bit_full_adder"
input = ["java", "-cp", "$digital", "CLI", "test", "1_bit_full_adder.dig", "-tests", "$project_tests/1bfa_test.dig"]
expected = """
1bfa_test: passed
"""
rubric = 25

[[tests]]
name = "8_bit_ripple_carry_adder"
input = ["java", "-cp", "$digital", "CLI", "test", "8_bit_ripple_carry_adder.dig", "-tests", "$project_tests/8brca_test.dig"]
expected = """
8brca_test: passed
"""
rubric = 25


[[tests]]
name = "8_bit_counter"
input = ["java", "-cp", "$digital", "CLI", "test", "8_bit_counter.dig", "-tests", "$project_tests/8bc_test.dig"]
expected = """
8bc_test: passed
"""
rubric = 25

